#: Theme
# include solarized_dark_theme.conf

#: Fonts {{{
# font_family JetBrainsMonoNL NFM
# font_family Hack Nerd Font Mono
font_family UbuntuMono Nerd Font
bold_font auto 
italic_font auto
bold_italic_font auto
font_size 13.0

#: }}}

#: Cursor customization {{{
shell_integration no-rc
cursor_shape block
cursor_blink_interval -1
cursor_stop_blinking_after 5

url_color #b58900
url_style dashed
detect_urls yes

#: }}}

#: Opacity {{{
dim_opacity 0.86
background_opacity 0.86
dynamic_background_opacity yes

#: }}}

#: Window config {{{
# remember_window_size yes
# hide_window_decorations no
# draw_minimal_borders yes
# tab_bar_margin_width 0.0

# window_resize_step_cells 2
# window_resize_step_lines 2
# 
# window_border_width 0.0
# window_margin_width 0.0
# window_padding_width 0.0
# 
box_drawing_scale 0.001, 0.70, 0.70, 0.70

#: }}}

#: Native Tabs config {{{
# tab_bar_edge top
# tab_bar_margin_width 1.0
# tab_bar_style powerline

#: }}}

#: Keyboard shortcuts {{{
clear_all_shortcuts yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map opt+k scroll_line_up
map opt+j scroll_line_down
map opt+u scroll_page_up
map opt+d scroll_page_down
map opt+shift+k change_font_size all +1.0
map opt+shift+j change_font_size all -1.0
map opt+shift+space change_font_size all 0
map opt+insert kitten unicode_input

#: }}}

term xterm-kitty
repaint_delay 10
input_delay 3
sync_to_monitor no
enable_audio_bell no
strip_trailing_spaces never
scrollback_lines 5000
copy_on_select yes
disable_ligatures never
select_by_word_characters :@-./_~?&=%+#
close_on_child_death yes

# Tango Dark theme
background            #000000
foreground            #e6e6e6
cursor                #e6e6e6
selection_background  #b4d5ff
color0                #000000
color8                #545753
color1                #cc0000
color9                #ef2828
color2                #4e9a05
color10               #8ae234
color3                #c4a000
color11               #fce94e
color4                #3464a4
color12               #719ecf
color5                #74507a
color13               #ad7ea7
color6                #05989a
color14               #34e2e2
color7                #d3d7cf
color15               #ededec
selection_foreground  #000000

# vim:ft=conf
