## name: Solarized Osaka Dark
## author: Derived from solarized-osaka
## license: MIT
## upstream: https://github.com/craftzdog/solarized-osaka.nvim
## blurb: A modern Solarized dark theme based on the Solarized Osaka Neovim colors.

#: The basic colors

foreground                      #9fabad
background                      #001419
selection_foreground            #001419
selection_background            #b28600


#: Cursor colors

cursor                          #859900
cursor_text_color               #00141a
cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #278bd3


#: kitty window border colors and terminal bell colors

active_border_color             #586e74
inactive_border_color           #002d38
bell_border_color               #dc312e
visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color          #00141a
macos_titlebar_color            #00141a


#: Tab bar colors

active_tab_foreground           #00141a
active_tab_background           #ca4c16
inactive_tab_foreground         #9fabad
inactive_tab_background         #073541
tab_bar_background              #00141a
tab_bar_margin_color            #00141a


#: Colors for marks (marked text in the terminal)

mark1_foreground black
mark1_background #2aa298
mark2_foreground black
mark2_background #d33682
mark3_foreground black
mark3_background #278bd3


#: The basic 16 colors

#: black
color0 #00141a
color8 #073541

#: red
color1 #dc312e
color9 #f65351

#: green
color2  #859900
color10 #b7fa00

#: yellow
color3  #b28600
color11 #ffbf00

#: blue
color4  #278bd3
color12 #47adf5

#: magenta
color5  #d33682
color13 #f254a1

#: cyan
color6  #2aa298
color14 #2beede

#: white
color7  #9fabad
color15 #ede7d4


# vim:ft=kitty
