#!/usr/bin/env bash
FILE_PATH="${1}"

WIDTH="${2}"
HEIGHT="${3}"

X="${4}"
Y="${5}"

if ! [ -f "$FILE_PATH" ] && ! [ -h "$FILE_PATH" ]; then
  exit
fi

kpreview() {
  kitty +kitten icat --silent --stdin=no --transfer-mode=file --place "${WIDTH}x${HEIGHT}@${X}x${Y}" "${1}" < /dev/null > /dev/tty
}

IMAGE_CACHE_PATH="$(hash "$FILE_PATH")"
TEMPDIR=$HOME/.cache
MIME_TYPE="$(file --dereference --brief --mime-type -- "${FILE_PATH}")"

case "${MIME_TYPE}" in
  application/x-gtar|application/gtar|application/x-tar|application/tar)
    tar tf "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/x-gzip|application/gzip)
    tar -ztf "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/x-bzip2|application/bzip2)
    tar -jtf "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/x-xz|application/x-7z-compressed|application/x-zstd)
    tar -Jtf "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/zip)
    unzip -l "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/x-rar|application/rar)
    unrar l "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/zstd)
    tar --use-compress-program=zstd -tf "$FILE_PATH" | head -n 100 | sed 's/$/.../' ;;
  application/font-*|font/*) # adicionado suporte para arquivos de fontes de texto
    thumbnail="$TEMPDIR/thumbnail.png"
    fontpreview "$FILE_PATH" -p -o "$thumbnail" -s 64 -w 400 -h 200
    kpreview "$thumbnail"
    sleep 0.6 ; rm -r "$thumbnail"
    ;;
  video/*)
    thumbnail="$TEMPDIR/thumbnail.png"
    ffmpeg -y -i "$FILE_PATH" -vframes 1 "$thumbnail"
    convert "$thumbnail" -resize "${WIDTH}x${HEIGHT}"\! "$thumbnail"
    kpreview "$thumbnail"
    sleep 0.6 ; rm -r "$thumbnail"
    ;;
  audio/*)
    thumbnail="$TEMPDIR/thumbnail.txt"
    ffprobe "$FILE_PATH" 2>&1 > "$thumbnail"
    kpreview "$thumbnail"
    ;;
  image/gif)
    thumbnail="$TEMPDIR/thumbnail.png"
    convert "$FILE_PATH[0]" -resize "${WIDTH}x${HEIGHT}"\! "$thumbnail"
    kpreview "$thumbnail"
    sleep 0.6 ; rm -r "$thumbnail"
    ;;
  image/*)
    thumbnail="$TEMPDIR/thumbnail.png"
    convert "$FILE_PATH" -resize "${WIDTH}x${HEIGHT}"\! "$thumbnail"
    kpreview "$thumbnail"
    sleep 0.6 ; rm -r "$thumbnail"
    ;;
  application/pdf)
    thumbnail="$TEMPDIR/thumbnail.png"
    pdftoppm -png -f 1 -singlefile "$FILE_PATH" "$TEMPDIR/preview"
    convert "$TEMPDIR/preview.png" -resize "${WIDTH}x${HEIGHT}"\! "$thumbnail"
    kpreview "$thumbnail"
    sleep 0.6 ; rm -r "$thumbnail"
    ;;
  *) cat -n "$FILE_PATH" ;;
esac
return 127 # nonzero retcode required for lf previews to reload
