# mpv keybindings

# Increase / decrease subtitle font size
/ add sub-scale +0.1
? add sub-scale -0.1

# AO volume controls (numpad):
+ add ao-volume  5
- add ao-volume -5

# Cycle video aspect ratios; "-1" is the container aspect
A cycle-values video-aspect "16:9" "16:10" "4:3" "2.35:1" "-1"

# Disable mouse whell
WHEEL_UP ignore
WHEEL_DOWN ignore
WHEEL_LEFT ignore
WHEEL_RIGHT ignore

n cycle chapter
N cycle chapter -1

# skip to next/previous file
> playlist-next
< playlist-prev


Alt+LEFT script-message Cycle_Video_Rotate "counter-clockwise"
Alt+RIGHT script-message Cycle_Video_Rotate "clockwise"

# mpvacious keybindings
a            script-binding mpvacious-menu-open
Ctrl+g       script-binding mpvacious-animated-snapshot-toggle
Ctrl+n       script-binding mpvacious-export-note
Ctrl+b       script-binding mpvacious-update-selected-note
Ctrl+B       script-binding mpvacious-overwrite-selected-note
Ctrl+m       script-binding mpvacious-update-last-note
Ctrl+M       script-binding mpvacious-overwrite-last-note
g            script-binding mpvacious-quick-card-menu-open
Alt+g        script-binding mpvacious-quick-card-sel-menu-open
Ctrl+c       script-binding mpvacious-copy-primary-sub-to-clipboard
Ctrl+C       script-binding mpvacious-copy-secondary-sub-to-clipboard
Ctrl+t       script-binding mpvacious-autocopy-toggle
H            script-binding mpvacious-sub-seek-back
L            script-binding mpvacious-sub-seek-forward
Alt+h        script-binding mpvacious-sub-seek-back-pause
Alt+l        script-binding mpvacious-sub-seek-forward-pause
Ctrl+h       script-binding mpvacious-sub-rewind
Ctrl+H       script-binding mpvacious-sub-replay
Ctrl+L       script-binding mpvacious-sub-play-up-to-next
Ctrl+v       script-binding mpvacious-secondary-sid-toggle
Ctrl+k       script-binding mpvacious-secondary-sid-prev
Ctrl+j       script-binding mpvacious-secondary-sid-next

# vim-like seeking (recommended by mpvacious)
l seek 5
h seek -5
j seek -60
k seek 60

# Cycle between subtitle files
K cycle sub
J cycle sub down

# Add/subtract 50 ms delay from subs
Z add sub-delay +0.05
z add sub-delay -0.05

# Adjust timing to previous/next subtitle
X sub-step 1
x sub-step -1
