# _+_+_+_+ General _+_+_+_+_
set-option -ga terminal-overrides ",xterm-256color:Tc"
setw -q -g utf8 on
set -g focus-events on

# Bind to execute programming codes
bind-key C-j run-shell "tmux send-keys -t 2 'clear ; gcc -g -lm ./main.c -o main && ./main' C-m "
bind-key C-k run-shell "tmux send-keys -t 2 'clear ; gcc -g -lm ./main.c -o main && ./main < input.txt' C-m "

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Resizing pane
bind -n C-Left resize-pane -L 2
bind -n C-Right resize-pane -R 2
bind -n C-Up resize-pane -U 2
bind -n C-Down resize-pane -D 2

# Bind to update key
bind-key u source-file ~/.config/tmux/tmux.conf \; display-message "Config updated!"
set -g repeat-time 0
set -sg escape-time 0

# Display
set -g set-titles on
set -g base-index 1
setw -g pane-base-index 1
set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'
set -g renumber-windows on
set -g history-limit 1000

# Navigation
set -g mouse on		# Mouse integration
set -g status-keys vi		# Set vi as the default editor

# Open another pane in the same path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection

set -g set-clipboard external
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -i -selection clipboard'
bind-key -n M-p run "tmux set-buffer \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"

# Turn a pane into a window
bind-key B break-pane -d

# My Vars ------------------

# Colorscheme
color_fg=#24273a
color_bg=#00222b
color_border_fg=${color_bg}
color_border_bg=terminal
cl_number_pcurrent="#[fg=#00222b]#[bold]#[bg=#dc322f]"
cl_number_pane="#[fg=#00222b]#[nobold]#[bg=#268bd2]"
cl_name_pcurrent="#[fg=#eee8d5]#[bold]#[bg=#585b70]"
cl_name_pane="#[fg=#eee8d5]#[nobold]#[bg=#657b83]"
color_session="#[fg=#00222b]#[bold]#[bg=#859900]"
color_prefix="#[fg=#00222b,bold,bg=#93a1a1]"
cl_cursor_pane_status="#[fg=#00222b]#[bold]#[bg=#b58900]"
color_reset="#[fg=#00222b]#[bg=default]"

# Char separator
right_sep="${color_reset}█"

#Indicators (vars)
ind_session="${color_session} [#S] ${right_sep}"
ind_current_pane="${right_sep}${cl_name_pcurrent} #W ${cl_number_pcurrent} #I "
ind_panes="${right_sep}${cl_name_pane} #W ${cl_number_pane} #I "

ind_prefix="${color_prefix}#{?client_prefix,   ,}"
ind_status_cursor_pane="${cl_cursor_pane_status} 󱂬 Window:[#P]  Pane:[#{window_panes}] "

# =================
# Status bar Colors
set -g status-style "fg=${color_fg},bg=${color_bg}"

# Status bar Left Side
set -g status-left-length 20
set -g status-left "${ind_session}"

# Windows Status
set -g status-interval 2
set -g status-justify "left"
set -g window-status-format "${ind_panes}"
set -g window-status-current-format "${ind_current_pane}"
#set -g window-status-separator "#[bg=#1B1B1C]"

# Status bar config right side
set -g status-right-length 40
set -g status-right "${ind_prefix}${ind_status_cursor_pane}"

# Border pane
set -g pane-border-lines simple
set -g pane-border-style "fg=#657b83"
set -g pane-active-border-style "fg=#859900"
