# _+_+_+_+ General _+_+_+_+_
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

setw -q -g utf8 on
set -g focus-events on

# Open current directory
# bind o run-shell "thunar #{pane_current_path}"
# bind -r e kill-pane -a

# Bind para enviar comando para painel 2 e salvar no arquivo de configuração
#bind-key C-s run-shell "tmux select-pane -t 2 ; tmux send-keys 'll' C-m ; tmux save-buffer ~/.tmux.conf"
#bind-key u run-shell "tmux select-pane -t 2 ; tmux send-keys 'll' C-m "
bind-key u run-shell "tmux send-keys -t 2 'clear ; gcc -g ./main.c -o main && ./main < input.txt' C-m "

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Resizing pane
bind -n C-Left resize-pane -L 2
bind -n C-Right resize-pane -R 2
bind -n C-Up resize-pane -U 2
bind -n C-Down resize-pane -D 2

# bind reload key
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
set -g repeat-time 0
set -sg escape-time 0

# Display
set -g set-titles on          # set terminal title
set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows
set -g automatic-rename on   # rename window to reflect current program
set -g automatic-rename-format '#{pane_current_command}'
set -g renumber-windows on    # renumber windows when a window is closed
set -g history-limit 1000	# boost history

# Navigation
set -g mouse on		# Mouse integration
set -g status-keys vi		# Set vi as the default editor

# Open another pane in the same path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -n M-v run "tmux set-buffer \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"


# My Vars ------------------

# Colorscheme
color_fg=#fdf6e3
color_bg=#859900
color_border_fg=${color_bg}
color_border_bg=terminal
color_windows="#[fg=color247,bg=color238]"
color_wcurrent="#[fg=#fdf6e3,bold,bg=color23]"
color_prefix="#[fg=#fdf6e3,bold,bg=color161]"
color_reset="#[fg=default]#[bg=default]"
tg_right_cw="#[fg=color23,nobold,bg=#859900]"
tg_right_invert_cw="#[fg=#859900,nobold,bg=color23]"
tg_right_w="#[fg=color238,bg=#859900,nobold]"
tg_right_invert_w="#[fg=#859900,bg=color238,nobold]"
tg_right_session="#[fg=#93a1a1,bg=#859900,nobold]"
tg_left_prefix="#[fg=color161,bold,bg=#859900]"
tg_left_sep="#[fg=color238]#[fg=#93a1a1,bg=color238]"
sides_color="#[fg=#002b36,bold,bg=#93a1a1]"

# Var to indicators
ind_prefix="${color_prefix}#{?client_prefix, דּ  ,}"
ind_panes="${sides_color}  Panel [#P:#{window_panes}] "

# Status bar Colors
set -g status-style "fg=${color_fg}, bg=${color_bg}"

# Status bar config left side
set -g status-left-length 40
set -g status-left "${sides_color} [#S] ${tg_right_session}"

# Windows Status
set -g status-interval 2
set -g status-justify "left"
set -g window-status-separator "#[bg=#859900]"
set -g window-status-format "${tg_right_invert_w}${color_windows} #I  #W ${tg_right_w}"
set -g window-status-current-format "${tg_right_invert_cw}${color_wcurrent} #I  #W ${tg_right_cw}"

# Status bar config right side
set -g status-right-length 40
set -g status-right "${tg_left_prefix}${ind_prefix}${tg_left_sep}${ind_panes}"

# Border pane
set -g pane-border-lines simple
set -g pane-border-style "fg=${color_border_bg}"
set -g pane-active-border-style "fg=${color_border_fg}"
