#!/bin/sh

# xinitrc runs automatically when you run startx.
# https://wiki.archlinux.org/index.php/Xinit#xinitrc
export GDK_BACKEND=x11
export XDG_SESSION_TYPE=x11

# xinitrc.d and xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset r rate 300 50 &

# Exec xprofile file
. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

#${WM:-i3}
