#!/bin/sh

# xinitrc
# xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Fcitx
# https://wiki.archlinux.org/index.php/Fcitx
find_fcitx() {
	for cmd in fcitx5 fcitx; do
		command -v "$cmd" && return
	done
}

if [ -n "${fcitx:=$(find_fcitx)}" ]; then
	# Define the environment variables to register the input method modules.
	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	export XMODIFIERS=@im=fcitx
	setxkbmap -model pc104 \
		  -layout us \
		  -variant altgr-intl \
	"$fcitx" -dr &
else
	setxkbmap -model pc104 \
		  -layout us,br \
		  -variant altgr-intl,winkeys \
fi

# Xresources
[[ -f ~/.config/X11/Xresources ]] && xrdb -load "${HOME}/.config/X11/Xresources"

# xprofile
[[ -f /etc/xprofile ]] && /etc/xprofile
# [[ -f ~/.config/X11/xprofile ]] && "${HOME}/.config/X11/xprofile"
. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

#-option terminate:ctrl_alt_bksp,caps:escape
#-option caps:escape,grp:alt_shift_toggle
#ssh-agent "${WM:-i3}"
