#!/bin/sh

# load Xresources
# xrdb -load ~/.config/X11/Xresources

# set wallpaper
# feh --bg-fill --randomize ~/Pictures/backgrounds/* &
# nitrogen --set-scaled --random /home/void/Pictures/Wallpapers
nitrogen --restore &

# Network Manager Applet
# nm-applet --indicator &
nm-applet &

# Bluetooth systray icon
blueman-applet &

# Compositor
picom -b &

# Hide mouse when typing
xbanish &

# start redshift
redshift &

# for notification
dunst &

# Gnome polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Don't Randomly Turn off
# xset s off
# xset -dpms
# xset s noblank

# Speedy keys
xset r rate 300 40 &

# Environment variables set everywhere
export EDITOR="/usr/bin/nvim"
export TERMINAL="/usr/bin/alacritty"
export BROWSER="/usr/bin/firefox"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

# XDG Paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Others Paths
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export "$XDG_DATA_HOME/pki/nssdb"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
export HISTCONTROL=ignoredups:erasedups           # No duplicate entries

# Xorg Paths
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# PostgreSQL Paths
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"

# ASDF Paths
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export ASDF_PYTHON_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/pip/default-python-packages"
export ASDF_NPM_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/npm/default-npm-packages"
export ASDF_GEM_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/gem/default-gems"

# Remap caps to escape set a keyboard layout
# setxkbmap -option caps:escape
setxkbmap -option grp:alt_shift_toggle -option caps:swapescape -layout us,br -variant qwerty

# Mouse settings
xinput set-prop "2.4G Mouse" "libinput Accel Speed" -1.0 &
xinput set-prop "06CB0301:00 06CB:CD41 Touchpad" "libinput Natural Scrolling Enabled" 1 &

# Monitor Config
xrandr --auto --output eDP-1 --left-of HDMI-1

# zsh config dir
# export ZDOTDIR=$HOME/.config/zsh

# Strat i3
# exec i3
