#!/bin/sh

# Xorg sessions runs automatically when you run startx.
# https://wiki.archlinux.org/title/GNOME
export GDK_BACKEND=x11
export XDG_SESSION_TYPE=x11

# Scaling
# https://wiki.archlinux.org/title/HiDPI#Multiple_displays
export GDK_SCALE=1
export GDK_DPI_SCALE=1


# Fcitx
# https://wiki.archlinux.org/index.php/Fcitx
find_fcitx() {
	for cmd in fcitx5 fcitx; do
		command -v "$cmd" && return
	done
}
if [ -n "${fcitx:=$(find_fcitx)}" ]; then
        export GTK_IM_MODULE=fcitx
        export QT_IM_MODULE=fcitx
        export XMODIFIERS=@im=fcitx
        export SDL_IM_MODULE=fcitx
        export GLFW_IM_MODULE=ibus
        xset r rate 300 50
	setxkbmap -model pc104 \
		  -layout us,br \
		  -variant altgr-intl \
		  -option terminate:ctrl_alt_bksp,caps:swapescape
else
	setxkbmap -model pc104 \
		  -layout us,br \
		  -variant altgr-intl,winkeys \
		  -option terminate:ctrl_alt_bksp,caps:swapescape,grp:win_space_toggle  # Adicionado caps:swapescape
fi

userresources="${HOME}/.config/X11/Xresources"
usermodmap="${HOME}/.config/X11/Xmodmap"

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# Activate dbus variables
dbus-update-activation-environment --all
