#!/bin/sh

# Xresources
[[ -f ~/.config/x11/Xresources ]] && xrdb -load "${HOME}/.config/x11/Xresources"

xset r rate 300 50 &

# Run localectl set-x11-keymap us "" "" caps:swapescape
# or /usr/share/X11/xkb/symbols/pc
# setxkbmap -option caps:swapescape

#Search for: Make xinput settings permanent after boot
xinput set-prop "06CB0301:00 06CB:CD41 Touchpad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "06CB0301:00 06CB:CD41 Touchpad" "libinput Tapping Enabled" 1 &
