# The  personal initialization file, executed for login shells.
# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) exit;;
esac


# Global tab size
#
# Set tab width system wide to 4 spaces (instead 8)
# @see man tabs
tabs -4 > /dev/null


# Shell options
shopt -s nocaseglob checkwinsize autocd cdspell \
  globstar histappend extglob dotglob direxpand \
  histverify lithist cmdhist

complete -cf doas
set -o noclobber

#
# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        source /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        source /etc/bash_completion
    fi
fi



###
### Includes
###
########################

##
## Source non-login shell config files
if [ -d "${XDG_CONFIG_HOME}/bash/config/bashrc.d/" ]; then
    for f in ${XDG_CONFIG_HOME}/bash/config/bashrc.d/*.bash ; do
        source "${f}"
    done
fi


###
### TMUX
###
########################

# Start tmux for every new terminal
# if [[ -z "${TMUX}" ]] ;then
#     # get the id of a deattached session
#     SESS_ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )"

#     # if not available create a new one
#     if [[ -z "${SESS_ID}" ]] ;then
#         exec tmux -2 -u new-session
#     # if detached session available attach to it
#     else
#         exec tmux -2 -u attach-session -t "${SESS_ID}"
#     fi
# fi
