#
# @file:    ~/.bash_profile
# @invoker: Login shell
# @see:     https://unix.stackexchange.com/questions/38175
#


# Disable less history
# export LESSHISTFILE=/dev/null
export LESSHISTFILE=-
export LESSHISTSIZE=0


###
### Path's
###
########################

# Reset path (or else it gets longer each time this is sourced)
export PATH=$(getconf PATH)
export PATH="/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin"


###
### Default XDG path end clean up ${HOME}
###
########################
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_STATE_HOME="${HOME}/.local/state"


if [ -f ${XDG_CONFIG_HOME}/user-dirs.dirs ]; then
    . ${XDG_CONFIG_HOME}/user-dirs.dirs
    export XDG_DESKTOP_DIR
    export XDG_DOWNLOAD_DIR
    export XDG_TEMPLATES_DIR
    export XDG_PUBLICSHARE_DIR
    export XDG_DOCUMENTS_DIR
    export XDG_MUSIC_DIR
    export XDG_PICTURES_DIR
    export XDG_VIDEOS_DIR
fi



##
## Locale
##
########################

## General locale category to use.
## (All LC_* values)
export LANG=en_US.UTF-8


## Overwrite specific LC_* values
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_COLLATE="C"



##
## Bash History
##
########################


###
### What to save in the history file?
###
### * ignorespace	Ignore commands starting with space
### * ignoredups	Ignore duplicate commands
### * erasedups		If current command is already in history, remove old entries
###					and keep the new entry.
###					(Only stores latest version of command)
export HISTCONTROL="ignorespace:ignoredups:erasedups"


## How many lines to save in the history file
export HISTFILESIZE=5000


## How many lines to remember in history list ($ history)
export HISTSIZE=5000


## Where to store the history file
export HISTFILE="${XDG_CACHE_HOME}/bash/bash_history"
if [ ! -d "$( dirname "${HISTFILE}" )" ]; then
    mkdir -p "$( dirname "${HISTFILE}" )"
fi

if [ ! -f "${HISTFILE}" ]; then
    touch "${HISTFILE}"
fi


## Set the history timestamp format to include date and time with seconds
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S: "


# FZF default options
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"


# Fix adding quotes around names with spaces
# https://unix.stackexchange.com/questions/258679/why-is-ls-suddenly-wrapping-items-with-spaces-in-single-quotes
export QUOTING_STYLE=literal


# Fix QT themes on GTK Desktops
# https://tatsumoto.neocities.org/blog/setting-up-anki.html#gtk-theme
export QT_QPA_PLATFORMTHEME=qt5ct


# Limits recursive functions, see 'man bash'
[[ -z "$FUNCNEST" ]] && export FUNCNEST=100



##
## Default Programs
##
########################

## Login terminal type
export TERM="xterm-kitty"
export COLORTERM=truecolor

## Default Editor
export EDITOR="nvim"

## Visual editor
export VISUAL="nvim"

## Default Viewer (manpage, etc)
export PAGER="less"

## Non standard default programs
export WM="i3"
export OPENER="xdg-open"
export TERMINAL="/usr/bin/kitty"
export TERMINAL_PROG="/usr/bin/kitty"
export SYSTEMD_EDITOR="nvim"
export READER="/usr/bin/zathura"
export AUDIO_PLAYER="/usr/bin/mpv"
export VIDEO_PLAYER="/usr/bin/mpv"



###
### Includes
###
########################


### Source non-login shell config file
if [ -n "$BASH_VERSION" ]; then
  if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
  fi
fi


## Source login-shell config files
if [ -d "${XDG_CONFIG_HOME}/bash/config/bash_profile.d/" ]; then
    for f in ${XDG_CONFIG_HOME}/bash/config/bash_profile.d/*.bash ; do
        source "${f}"
    done
fi


## ASDF Setup
[[ -f "/opt/asdf-vm/asdf.sh" ]] && source /opt/asdf-vm/asdf.sh


## Java Setup for asdf
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=gasp -Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java"
if [[ -f "${HOME}/.local/share/asdf/plugins/java/set-java-home.bash" ]]; then
    source "${HOME}/.local/share/asdf/plugins/java/set-java-home.bash"
fi


## Completions
[[ -f "/usr/share/git/completion/git-prompt.sh" ]] && source /usr/share/git/completion/git-prompt.sh
[[ -f "/usr/share/git/completion/git-completion.bash" ]] && source /usr/share/git/completion/git-completion.bash
[[ -f "/usr/share/bash-completion/completions/git" ]] && source /usr/share/bash-completion/completions/git


# Start graphical server on tty1 if not already running.
# https://wiki.archlinux.org/index.php/Xinit#Autostart_X_at_login
export XINITRC="${HOME}/X11/xinitrc"
if [[ -z "${DISPLAY}" ]] && [[ "${XDG_VTNR}" -eq 1 ]]; then
    startx "$XINITRC"
fi
