Section "Monitor"
    Identifier "eDP-1"
    Option "DPMS" "true"
    Option "StandbyTime" "5"
    Option "SuspendTime" "6"
    Option "BlankTime"  "6"
    Option "OffTime" "7"
EndSection

Section "ServerLayout"
    Identifier "ServerLayout0"
    Option "StandbyTime" "5"
    Option "SuspendTime" "6"
    Option "BlankTime"  "6"
    Option "OffTime" "7"
EndSection
